// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://awjqnecxydhvhtefbqli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3anFuZWN4eWRodmh0ZWZicWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NjA5MTAsImV4cCI6MjA3MDUzNjkxMH0.F1JKCSNN9n37AzJhVCRcEOgdDrvqbWubse2YBQAze7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});